# Conversion
markdown:           kramdown
highlighter:        rouge
kramdown:
  input:            GFM


# Permalinks
permalink:        pretty

# Setup
title:            QFlex
tagline:          'Quick & Flexible Computer Architecture Simulator'
description:      'Quick & Flexible Computer Architecture Simulator'
url:              http://parsalab.github.io/qflex/
baseurl:          /qflex/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         3
paginate_path:    blog/page:num

# Custom vars
version:          1.0
blog_path:        blog/
excerpt_separator: <!--more-->

github:
  repo:           https://github.com/parsalab/qflex

# Handling Reading
exclude: 			 [old]

gems: [jekyll-paginate, jekyll-gist]
